config/routes.rb
Lm3::Application.routes.draw do
  get "users/new"

  resources :users

  get "frontend/list"

  get "frontend/listen"

  resources :beats

  root :to => 'frontend#list', :as => 'list'
end

app/models/beat.rb
class Beat < ActiveRecord::Base
  attr_accessible :creator, :length, :title
end

app/models/identity.rb
# identity.rb
# 
#
# Created by The Hhonus on 7/27/12.
# Copyright 2012 __MyCompanyName__. All rights reserved.

class Identity < OmniAuth::Identity::Models::ActiveRecord

   include OmniAuth::Identity

  field :email, type: String
  field :name, type: String
  field :password_digest, type: String

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password
 
  before_save { |user| user.email = email.downcase }
 
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-,]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                    format: { with: VALID_EMAIL_REGEX },
  				    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/beats_controller.rb
class BeatsController < ApplicationController
  # GET /beats
  # GET /beats.json
  def index
    @beats = Beat.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @beats }
    end
  end

  # GET /beats/1
  # GET /beats/1.json
  def show
    @beat = Beat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @beat }
    end
  end

  # GET /beats/new
  # GET /beats/new.json
  def new
    @beat = Beat.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @beat }
    end
  end

  # GET /beats/1/edit
  def edit
    @beat = Beat.find(params[:id])
  end

  # POST /beats
  # POST /beats.json
  def create
    @beat = Beat.new(params[:beat])

    respond_to do |format|
      if @beat.save
        format.html { redirect_to @beat, notice: 'Beat was successfully created.' }
        format.json { render json: @beat, status: :created, location: @beat }
      else
        format.html { render action: "new" }
        format.json { render json: @beat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /beats/1
  # PUT /beats/1.json
  def update
    @beat = Beat.find(params[:id])

    respond_to do |format|
      if @beat.update_attributes(params[:beat])
        format.html { redirect_to @beat, notice: 'Beat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @beat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beats/1
  # DELETE /beats/1.json
  def destroy
    @beat = Beat.find(params[:id])
    @beat.destroy

    respond_to do |format|
      format.html { redirect_to beats_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController
  def list
  
  @beats = Beat.all
  
  
  
  end

  def listen
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beats_helper.rb
module BeatsHelper
end

app/helpers/frontend_helper.rb
module FrontendHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/beats/_form.html.erb
<%= form_for(@beat) do |f| %>
  <% if @beat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beat.errors.count, "error") %> prohibited this beat from being saved:</h2>

      <ul>
      <% @beat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :length %><br />
    <%= f.text_field :length %>
  </div>
  <div class="field">
    <%= f.label :creator %><br />
    <%= f.text_field :creator %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beats/edit.html.erb
<h1>Editing beat</h1>

<%= render 'form' %>

<%= link_to 'Show', @beat %> |
<%= link_to 'Back', beats_path %>

app/views/beats/index.html.erb
<h1>Listing beats</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Length</th>
    <th>Creator</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @beats.each do |beat| %>
  <tr>
    <td><%= beat.title %></td>
    <td><%= beat.length %></td>
    <td><%= beat.creator %></td>
    <td><%= link_to 'Show', beat %></td>
    <td><%= link_to 'Edit', edit_beat_path(beat) %></td>
    <td><%= link_to 'Destroy', beat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Beat', new_beat_path %>

app/views/beats/new.html.erb
<h1>New beat</h1>

<%= render 'form' %>

<%= link_to 'Back', beats_path %>

app/views/beats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @beat.title %>
</p>

<p>
  <b>Length:</b>
  <%= @beat.length %>
</p>

<p>
  <b>Creator:</b>
  <%= @beat.creator %>
</p>


<%= link_to 'Edit', edit_beat_path(@beat) %> |
<%= link_to 'Back', beats_path %>

app/views/frontend/list.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <!-- This page is copyright Elated Communications Ltd. (www.elated.com) -->

    <title>Riff-bay</title>

    <style type="text/css">
      body { font-size: 80%; font-family: 'Lucida Grande', Verdana, Arial, Sans-Serif; }
      ul#tabs { list-style-type: none; margin: 30px 0 0 0; padding: 0 0 0.3em 0; }
      ul#tabs li { display: inline; }
      ul#tabs li a { color: #42454a; background-color: #dedbde; border: 1px solid #c9c3ba; border-bottom: none; padding: 0.3em; text-decoration: none; }
      ul#tabs li a:hover { background-color: #f1f0ee; }
      ul#tabs li a.selected { color: #000; background-color: #f1f0ee; font-weight: bold; padding: 0.7em 0.3em 0.38em 0.3em; }
      div.tabContent { border: 1px solid #c9c3ba; padding: 0.5em; background-color: #f1f0ee; text-align:center; padding: 10px}
      div.tabContent.hide { display: none; }
    </style>

    <script type="text/javascript">
    //<![CDATA[

    var tabLinks = new Array();
    var contentDivs = new Array();

    function init() {

      // Grab the tab links and content divs from the page
      var tabListItems = document.getElementById('tabs').childNodes;
      for ( var i = 0; i < tabListItems.length; i++ ) {
        if ( tabListItems[i].nodeName == "LI" ) {
          var tabLink = getFirstChildWithTagName( tabListItems[i], 'A' );
          var id = getHash( tabLink.getAttribute('href') );
          tabLinks[id] = tabLink;
          contentDivs[id] = document.getElementById( id );
        }
      }

      // Assign onclick events to the tab links, and
      // highlight the first tab
      var i = 0;

      for ( var id in tabLinks ) {
        tabLinks[id].onclick = showTab;
        tabLinks[id].onfocus = function() { this.blur() };
        if ( i == 0 ) tabLinks[id].className = 'selected';
        i++;
      }

      // Hide all content divs except the first
      var i = 0;

      for ( var id in contentDivs ) {
        if ( i != 0 ) contentDivs[id].className = 'tabContent hide';
        i++;
      }
    }

    function showTab() {
      var selectedId = getHash( this.getAttribute('href') );

      // Highlight the selected tab, and dim all others.
      // Also show the selected content div, and hide all others.
      for ( var id in contentDivs ) {
        if ( id == selectedId ) {
          tabLinks[id].className = 'selected';
          contentDivs[id].className = 'tabContent';
        } else {
          tabLinks[id].className = '';
          contentDivs[id].className = 'tabContent hide';
        }
      }

      // Stop the browser following the link
      return false;
    }

    function getFirstChildWithTagName( element, tagName ) {
      for ( var i = 0; i < element.childNodes.length; i++ ) {
        if ( element.childNodes[i].nodeName == tagName ) return element.childNodes[i];
      }
    }

    function getHash( url ) {
      var hashPos = url.lastIndexOf ( '#' );
      return url.substring( hashPos + 1 );
    }

    //]]>
    </script>
  </head>
  <body onload="init()">
    <h1>Riff-bay</h1>

    <ul id="tabs">
      <li><a href="#beats">Beats</a></li>
      <li><a href="#guitar">Guitar</a></li>
      <li><a href="#bass">Bass</a></li>
    </ul>

 <div class="tabContent" id="beats">
   <h2>Beats</h2>
   <div>
     <table>
<tr><th>Listen</th>
	<th>Title</th>
    <th>Length</th>
    <th>Creator</th>
    <th>Download <p>(Low Res Free)</th>
    <th>Download <p>(Hi Res Free)</th>
 </tr>   
    <% @beats.each do |beat| %>
 <tr>
 <td><img src="audio-headset (4).png" height=10px width=10px;>
 <td><%= beat.title.to_s %>
 <td><%= beat.length.to_s  %>
 <td><%= beat.creator.to_s %>
 </tr>
 <% end  %>
  </table>
</div> 
      </div>
    
 
    <div class="tabContent" id="guitar">
      <h2>Guitar</h2>
      <div>
        <table>
          <tr><th>Listen</th>
          		<th>Title</th>
          		<th>Length</th>
          		<th>Creator</th>
          		<th>Download Low Res Free</th>
          		<th>Download Hi Res (Pay)</th>
          </tr>
          <tr><td> <img src="audio-headset (4).png" height=10px width=10px;>
              <td> Guitar
              <td> 3:42
              <td> Maxxy
              <td> <img src="download-3 (2).png" height=10px width=10px;>
              <td> <img src="download-3 (2).png" height=10px width=10px;>              
          </tr>
          <tr>
          <tr><td> <img src="audio-headset (4).png" height=10px width=10px;>
          	  <td> Guitar-o
              <td> 2:42
              <td> Maximo
              <td> <img src="download-3 (2).png" height=10px width=10px;>
              <td> <img src="download-3 (2).png" height=10px width=10px;>              
          </tr>
        </table>
      </div>
    </div>

    <div class="tabContent" id="bass">
      <h2>Bass</h2>
     <div>
        <table>
          <tr><th>Listen</th>
          		<th>Title</th>
          		<th>Length</th>
          		<th>Creator</th>
          		<th>Download Low Res Free</th>
          		<th>Download Hi Res (Pay)</th>
          </tr>
          <tr><td> <img src="audio-headset (4).png" height=10px width=10px;>
              <td> A Bass Too Far
              <td> 1:56
              <td> Bassy
              <td> <img src="download-3 (2).png" height=10px width=10px;>
              <td> <img src="download-3 (2).png" height=10px width=10px;>
          </tr>
          <tr>
          <tr><td> <img src="audio-headset (4).png" height=10px width=10px;>
          	  <td> One Bass
              <td> 1:34
              <td> Saltiffo
              <td> <img src="download-3 (2).png" height=10px width=10px;>
              <td> <img src="download-3 (2).png" height=10px width=10px;>
          </tr>
        </table>
      </div>
    </div>

 
  </body>
</html>

app/views/frontend/listen.html.erb
<h1>Frontend#listen</h1>
<p>Find me in app/views/frontend/listen.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lm3</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>